// SPDX-License-Identifier: LGPL-3.0-or-later
// Copyright (c) 2020–2026 Michal Dengusiak & Jakub Ziolkowski and contributors

using System;
using System.Collections.Generic;
using System.Linq;

namespace SAM.Analytical
{
    public static partial class Modify
    {
        /// <summary>
        /// Accepts one dwelling's design airflow from another model of the same building - typically the model a
        /// completed Iteration 2B optimisation left - onto the clean baseline's own design terminals: the explicit
        /// "accept 2B for a dwelling" design edit of the mixed dwelling strategies (PR0 D3).
        ///
        /// <para><b>One airflow authority</b></para>
        /// <para>
        /// The accepted airflow is written to the baseline's <see cref="VentilationTerminal.DesignFlowRate_Lps"/> and
        /// nowhere else. Nothing is written to a <see cref="PartODwellingStrategy"/>: the caller records
        /// <see cref="Enums.PartODesignAirFlowBasis.RetainedDesign"/> with <see cref="PartODwellingDesignAcceptance.DesignFingerprint"/>
        /// as its guard, and <c>MaterialisePartODwellingStrategies</c> reads the airflow back from the terminals.
        /// </para>
        ///
        /// <para><b>Existing operations only</b></para>
        /// <list type="number">
        /// <item><b>Lineage.</b> Every design terminal the source states in the dwelling must realise exactly one
        /// continuous Approved Document F requirement of the baseline's space, matched on the requirement's regulatory
        /// identity (<see cref="PartFTerminalReference.Matches"/> - room, role, source paragraph), never on a guid: the
        /// source's terminals are regenerated by every preparation. And every continuous requirement of the dwelling
        /// must be realised in the source - acceptance is whole-dwelling, a partial design is refused. An untraceable,
        /// ambiguous or airflow-less terminal refuses.</item>
        /// <item><b>Terminals.</b> <see cref="RealizePartFVentilationTerminals"/> scoped to the dwelling's spaces -
        /// terminals only, never internal conditions or systems, so the lossy rewrite of D1 does not return.</item>
        /// <item><b>Airflow.</b> Per space and direction, the source's total is written with
        /// <see cref="SetSpaceDesignFlowRate"/> - the same per-room, per-direction control Iteration 2B varies, with
        /// the same Approved Document F floor. Its refusal refuses the acceptance.</item>
        /// </list>
        ///
        /// <para><b>What it never does</b></para>
        /// <para>
        /// It never modifies the baseline or the source handed in, never touches another dwelling or any space outside
        /// this one, never reads or patches the source's systems, movements, results or scenarios, and never accepts
        /// onto a model that is not a clean pre-Part-O baseline (<see cref="Query.PartOBaselineFindings"/>). Balance of
        /// the accepted design is not restated here: <c>MaterialisePartODwellingStrategies</c> refuses a design whose
        /// air network does not balance.
        /// </para>
        /// </summary>
        /// <param name="analyticalModel_Baseline">The clean baseline. Not modified.</param>
        /// <param name="guid_Zone">The dwelling whose design is accepted.</param>
        /// <param name="analyticalModel_Source">The model stating the design, e.g. a 2B result. Only read.</param>
        /// <param name="tolerance_Lps">Airflows closer than this are the same number [l/s].</param>
        public static PartODwellingDesignAcceptance AcceptPartODwellingDesign(this AnalyticalModel analyticalModel_Baseline, Guid guid_Zone, AnalyticalModel analyticalModel_Source, double tolerance_Lps = 0.001)
        {
            PartODwellingDesignAcceptance result = new(guid_Zone);

            if (analyticalModel_Baseline is null)
            {
                result.Refusals.Add("No baseline was supplied to accept the design onto.");
                return result;
            }

            if (analyticalModel_Source is null)
            {
                result.Refusals.Add("No model was supplied to accept the design from.");
                return result;
            }

            //See Query.IsValidFlowRateTolerance: an infinite tolerance would call every airflow "the same" and accept nothing.
            if (!Query.IsValidFlowRateTolerance(tolerance_Lps))
            {
                result.Refusals.Add(string.Format("The airflow tolerance {0} is not a usable finite, non-negative number, so the design cannot be compared.", tolerance_Lps));
                return result;
            }

            if (!analyticalModel_Baseline.IsPartOCleanBaseline(out List<PartOMaterialisationRefusal> findings))
            {
                result.Refusals.Add(string.Format("The model accepting the design is not a clean Part O baseline, and a design is only ever accepted onto one: {0}", string.Join(" ", findings.ConvertAll(x => x.Message))));
                return result;
            }

            AdjacencyCluster adjacencyCluster = analyticalModel_Baseline.AdjacencyCluster;
            AdjacencyCluster adjacencyCluster_Source = analyticalModel_Source.AdjacencyCluster;

            List<Zone> zones_All = adjacencyCluster?.GetZones() ?? [];
            List<Zone> zones_Dwelling = Query.PartFDwellingZones(zones_All) ?? [];
            Zone zone = zones_Dwelling.Find(x => x.Guid == guid_Zone);
            if (zone is null)
            {
                result.Refusals.Add(string.Format("Zone {0} is not a dwelling of the baseline, so there is no dwelling design to accept.", guid_Zone));
                return result;
            }

            Zone zone_Source = adjacencyCluster_Source?.GetObject<Zone>(guid_Zone);
            if (zone_Source is null)
            {
                result.Refusals.Add(string.Format("The model to accept from does not contain dwelling '{0}', so it is not a model of this building.", zone.Name));
                return result;
            }

            List<Space> spaces = adjacencyCluster.GetRelatedObjects<Space>(zone) ?? [];
            spaces.Sort((x, y) => string.Compare(x?.Name, y?.Name, StringComparison.OrdinalIgnoreCase));

            HashSet<Guid> guids_Space = [.. spaces.Where(x => x is not null).Select(x => x.Guid)];

            //A space another owning zone also holds - another dwelling, or a classified common/non-dwelling zone such as a
            //corridor - has no single dwelling design: the materialisation refuses that state (OverlappingZones, over the
            //same ownership scope), so acceptance refuses it first.
            zones_All.PartFClassifyDwellingZones(out List<Zone> _, out List<Zone> zones_NotDwelling, out List<Zone> _);
            foreach (Zone zone_Other in zones_Dwelling.Concat(zones_NotDwelling ?? []))
            {
                if (zone_Other.Guid == guid_Zone)
                {
                    continue;
                }

                foreach (Space space_Other in adjacencyCluster.GetRelatedObjects<Space>(zone_Other) ?? [])
                {
                    if (space_Other is not null && guids_Space.Contains(space_Other.Guid))
                    {
                        result.Refusals.Add(string.Format("Space '{0}' belongs to both '{1}' and '{2}', so it has no single dwelling design to accept.", space_Other.Name, zone.Name, zone_Other.Name));
                    }
                }
            }

            if (result.Refusals.Count != 0)
            {
                return result;
            }
            HashSet<Guid> guids_Space_Source = [.. (adjacencyCluster_Source.GetRelatedObjects<Space>(zone_Source) ?? []).Where(x => x is not null).Select(x => x.Guid)];
            if (!guids_Space.SetEquals(guids_Space_Source))
            {
                result.Refusals.Add(string.Format("Dwelling '{0}' holds different spaces in the model to accept from than in the baseline, so the design cannot be traced room by room.", zone.Name));
                return result;
            }

            // ---- Lineage: every source terminal traced to a requirement, every requirement realised ----

            Dictionary<(Guid, FlowClassification), double> totals = [];

            foreach (Space space in spaces)
            {
                List<PartFVentilationTerminalRequirement> requirements = (space.GetValue<PartFSpaceData>(SpaceParameter.PartFSpaceData)?.Terminals ?? [])
                    .FindAll(x => x is not null && x.ContinuousDesignFlowRate_Lps.HasValue && !double.IsNaN(x.ContinuousDesignFlowRate_Lps.Value));

                Space space_Source = adjacencyCluster_Source.GetObject<Space>(space.Guid);
                List<VentilationTerminal> ventilationTerminals_Source = adjacencyCluster_Source.VentilationTerminals(space_Source) ?? [];

                HashSet<Guid> guids_Realised = [];

                foreach (VentilationTerminal ventilationTerminal_Source in ventilationTerminals_Source)
                {
                    if (ventilationTerminal_Source is null)
                    {
                        continue;
                    }

                    //Related to more than one room of the source, it would be counted once per room.
                    if ((adjacencyCluster_Source.GetRelatedObjects<Space>(ventilationTerminal_Source) ?? []).Count(x => x is not null) > 1)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the model to accept from is related to more than one space, so its airflow belongs to no single room.", ventilationTerminal_Source.Name, space.Name));
                        continue;
                    }

                    PartFTerminalReference partFTerminalReference = ventilationTerminal_Source.GetValue<PartFTerminalReference>(VentilationTerminalParameter.PartFTerminalReference);
                    if (partFTerminalReference is null)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the model to accept from realises no Approved Document F requirement, so its airflow cannot be traced to the baseline.", ventilationTerminal_Source.Name, space.Name));
                        continue;
                    }

                    List<PartFVentilationTerminalRequirement> requirements_Matched = requirements.FindAll(partFTerminalReference.Matches);
                    if (requirements_Matched.Count != 1)
                    {
                        result.Refusals.Add(string.Format(
                            requirements_Matched.Count == 0
                                ? "Design terminal '{0}' in space '{1}' of the model to accept from realises {2}, and the baseline's Approved Document F data for that space has no such continuous requirement."
                                : "Design terminal '{0}' in space '{1}' of the model to accept from realises {2}, which answers to more than one requirement of the baseline's space, so which one it realises is ambiguous.",
                            ventilationTerminal_Source.Name, space.Name, partFTerminalReference.Description()));
                        continue;
                    }

                    double? designFlowRate_Lps = ventilationTerminal_Source.DesignFlowRate_Lps;
                    if (!designFlowRate_Lps.HasValue || double.IsNaN(designFlowRate_Lps.Value) || designFlowRate_Lps.Value < 0)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the model to accept from states no usable design airflow.", ventilationTerminal_Source.Name, space.Name));
                        continue;
                    }

                    PartFVentilationTerminalRequirement requirement = requirements_Matched[0];
                    if (Direction(requirement) != ventilationTerminal_Source.FlowClassification)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the model to accept from is classified {2}, but realises the {3} requirement, which is {4}. Its airflow is not accepted in either direction.", ventilationTerminal_Source.Name, space.Name, ventilationTerminal_Source.FlowClassification, Core.Query.Description(requirement.TerminalRole), Direction(requirement)));
                        continue;
                    }

                    guids_Realised.Add(requirement.Guid);

                    (Guid, FlowClassification) key = (space.Guid, Direction(requirement));
                    totals[key] = (totals.TryGetValue(key, out double total) ? total : 0) + designFlowRate_Lps.Value;
                }

                foreach (PartFVentilationTerminalRequirement requirement in requirements)
                {
                    if (!guids_Realised.Contains(requirement.Guid))
                    {
                        result.Refusals.Add(string.Format("The model to accept from states no design terminal for the {0} requirement of space '{1}', so it holds no whole design for dwelling '{2}'. A partial design is not accepted.", Core.Query.Description(requirement.TerminalRole), space.Name, zone.Name));
                    }
                }
            }

            // ---- The baseline terminals the writes will touch ----

            foreach (Space space in spaces)
            {
                List<PartFVentilationTerminalRequirement> requirements = (space.GetValue<PartFSpaceData>(SpaceParameter.PartFSpaceData)?.Terminals ?? [])
                    .FindAll(x => x is not null && x.ContinuousDesignFlowRate_Lps.HasValue && !double.IsNaN(x.ContinuousDesignFlowRate_Lps.Value));

                //Every design terminal the baseline already carries must realise exactly one continuous requirement, in that
                //requirement's direction: SetSpaceDesignFlowRate spreads a total over EVERY terminal of the direction, so a
                //designer-added or intermittent device would take part of the accepted continuous design. Refused, never guessed.
                foreach (VentilationTerminal ventilationTerminal in adjacencyCluster.VentilationTerminals(space) ?? [])
                {
                    //Only where a write happens: a space the design writes, and there any lineage-tagged terminal (its lineage
                    //must be sound) or an untagged one in the direction written. An untagged terminal the writes never touch
                    //(a manual cupboard fan, an extract fan in a room whose supply is written) does not stand in the way.
                    if (ventilationTerminal is null || !totals.Keys.Any(x => x.Item1 == space.Guid))
                    {
                        continue;
                    }

                    if (ventilationTerminal.GetValue<PartFTerminalReference>(VentilationTerminalParameter.PartFTerminalReference) is null && !totals.ContainsKey((space.Guid, ventilationTerminal.FlowClassification)))
                    {
                        continue;
                    }

                    //A terminal also related to a space outside this dwelling would be rewritten for that space too (terminals
                    //are replaced by guid), so the other dwelling would change silently.
                    List<Space> spaces_Terminal = adjacencyCluster.GetRelatedObjects<Space>(ventilationTerminal) ?? [];
                    if (spaces_Terminal.Exists(x => x is not null && !guids_Space.Contains(x.Guid)))
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the baseline is also related to space '{2}', outside dwelling '{3}', so accepting a design onto it would change another dwelling. Give each space its own terminal first.", ventilationTerminal.Name, space.Name, spaces_Terminal.Find(x => x is not null && !guids_Space.Contains(x.Guid))!.Name, zone.Name));
                        continue;
                    }

                    //Related to two rooms of this dwelling, it would be written once per room.
                    if (spaces_Terminal.Count(x => x is not null) > 1)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' of the baseline is related to more than one space of dwelling '{1}', so its design airflow belongs to no single room. Give each space its own terminal first.", ventilationTerminal.Name, zone.Name));
                        continue;
                    }

                    PartFTerminalReference partFTerminalReference_Baseline = ventilationTerminal.GetValue<PartFTerminalReference>(VentilationTerminalParameter.PartFTerminalReference);
                    List<PartFVentilationTerminalRequirement> requirements_Baseline = partFTerminalReference_Baseline is null ? [] : requirements.FindAll(partFTerminalReference_Baseline.Matches);
                    if (requirements_Baseline.Count != 1 || Direction(requirements_Baseline[0]) != ventilationTerminal.FlowClassification)
                    {
                        result.Refusals.Add(string.Format("Space '{0}' of the baseline carries design terminal '{1}', which does not realise exactly one continuous Approved Document F requirement in its own direction, so an accepted airflow could not be placed on the requirement terminals alone. Remove it or link it to a requirement first.", space.Name, ventilationTerminal.Name));
                        continue;
                    }

                    //Checked here, before any write, so an unusable duty offset by another terminal (-5 and 25 summing to 20)
                    //is refused rather than redistributed.
                    double? designFlowRate_Baseline = ventilationTerminal.DesignFlowRate_Lps;
                    if (!designFlowRate_Baseline.HasValue || double.IsNaN(designFlowRate_Baseline.Value) || double.IsInfinity(designFlowRate_Baseline.Value) || designFlowRate_Baseline.Value < 0)
                    {
                        result.Refusals.Add(string.Format("Design terminal '{0}' in space '{1}' of the baseline states no usable design airflow ({2}), so the dwelling's design cannot be accepted onto it. Correct the terminal first.", ventilationTerminal.Name, space.Name, designFlowRate_Baseline?.ToString(System.Globalization.CultureInfo.InvariantCulture) ?? "none"));
                    }
                }

            }

            if (result.Refusals.Count != 0)
            {
                return result;
            }

            if (totals.Count == 0)
            {
                result.Refusals.Add(string.Format("Dwelling '{0}' has no continuous Approved Document F requirement, so there is no mechanical design to accept.", zone.Name));
                return result;
            }

            // ---- Terminals, scoped to the dwelling ----

            //Staged, and published only once every write has succeeded: the cluster is private, so a refusal discards all of it
            //and nothing may describe a change that was never kept.
            List<string> notes = [];
            List<PartODwellingDesignChange> changes = [];

            adjacencyCluster.RealizePartFVentilationTerminals(spaces, out List<string> notes_Realise, out List<string> refusals_Realise);
            notes.AddRange(notes_Realise);
            if (refusals_Realise.Count != 0)
            {
                result.Refusals.AddRange(refusals_Realise);
                return result;
            }

            // ---- Airflow, per space and direction ----

            foreach (Space space in spaces)
            {
                foreach (FlowClassification flowClassification in new[] { FlowClassification.Supply, FlowClassification.Extract })
                {
                    if (!totals.TryGetValue((space.Guid, flowClassification), out double total_Accepted))
                    {
                        continue;
                    }

                    Space space_Cluster = adjacencyCluster.GetObject<Space>(space.Guid);
                    double total_Before = (adjacencyCluster.VentilationTerminals(space_Cluster) ?? []).VentilationTerminals(flowClassification)?.Sum(x => x?.DesignFlowRate_Lps ?? 0) ?? 0;

                    //Always through the setter, even where the totals already agree: it is the operation that holds the
                    //Approved Document F floor and the terminal-duty rules, and a baseline can carry either state already.
                    adjacencyCluster.SetSpaceDesignFlowRate(space_Cluster, flowClassification, total_Accepted, out List<string> notes_Set, out List<string> refusals_Set, tolerance_Lps);
                    if (refusals_Set.Count != 0)
                    {
                        result.Refusals.AddRange(refusals_Set);
                        return result;
                    }

                    notes.AddRange(notes_Set);

                    //What was persisted, which is not always what was asked: SetSpaceDesignFlowRate raises a value a rounding
                    //bit below the Approved Document F floor to the floor exactly.
                    double total_After = (adjacencyCluster.VentilationTerminals(adjacencyCluster.GetObject<Space>(space.Guid)) ?? []).VentilationTerminals(flowClassification)?.Sum(x => x?.DesignFlowRate_Lps ?? 0) ?? total_Accepted;
                    //Every persisted difference is reported (beyond floating-point noise), however small: the model changed.
                    if (System.Math.Abs(total_After - total_Before) > 1e-9)
                    {
                        changes.Add(new PartODwellingDesignChange(space.Guid, space.Name, flowClassification, total_Before, total_After));
                    }
                }
            }

            AnalyticalModel analyticalModel = new(analyticalModel_Baseline, adjacencyCluster);

            //Defensive: terminals are baseline design data, so this holds by construction; never hand out a model that
            //would itself be refused as a baseline.
            if (!analyticalModel.IsPartOCleanBaseline(out List<PartOMaterialisationRefusal> findings_After))
            {
                result.Refusals.Add(string.Format("Accepting the design would leave a model that is not a clean baseline: {0}", string.Join(" ", findings_After.ConvertAll(x => x.Message))));
                return result;
            }

            result.Notes.AddRange(notes);
            result.Changes.AddRange(changes);
            result.AnalyticalModel = analyticalModel;
            result.DesignFingerprint = adjacencyCluster.PartODwellingDesignFingerprint(adjacencyCluster.GetObject<Zone>(guid_Zone));

            return result;
        }

        private static FlowClassification Direction(PartFVentilationTerminalRequirement partFVentilationTerminalRequirement) => partFVentilationTerminalRequirement.IsExtract ? FlowClassification.Extract : FlowClassification.Supply;
    }
}
