name: Build (Windows)

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    # Guard: run CI only in SAM-BIM org (prevents breaking upstream )
    if: github.repository_owner == 'SAM-BIM'

    runs-on: windows-2022

    strategy:
      fail-fast: false
      matrix:
        configuration: [ "Release" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        shell: pwsh
        env:
          MSBUILDDISABLENODEREUSE: "1"
        run: |
          $ErrorActionPreference = 'Stop'
          msbuild `
            '.\BuildAll_Release_net.csproj' `
            '/t:Restore' `
            '/m:1' '/nr:false' '/v:m' `
            "/p:Configuration=${{ matrix.configuration }}" `
            '/p:UseSharedCompilation=false'

      - name: Build
        shell: pwsh
        env:
          MSBUILDDISABLENODEREUSE: "1"
        run: |
          $ErrorActionPreference = 'Stop'
          msbuild `
            '.\BuildAll_Release_net.csproj' `
            '/t:Rebuild' `
            '/m:1' '/nr:false' '/v:m' `
            "/p:Configuration=${{ matrix.configuration }}" `
            '/p:UseSharedCompilation=false'
